language:
- clojure
- node_js

jdk:
- oraclejdk8

sudo: required

addons:
  postgresql: "9.5"

before_install:
- sudo /etc/init.d/postgresql stop
- sudo apt-get -y remove --purge postgresql-9.1
- sudo apt-get -y remove --purge postgresql-9.2
- sudo apt-get -y remove --purge postgresql-9.3
- sudo apt-get -y remove --purge postgresql-9.4
- sudo apt-get -y autoremove
- sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
- sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
- sudo apt-get update
- sudo apt-get -y install postgresql-9.5
- sudo sh -c 'echo "local all all trust" > /etc/postgresql/9.5/main/pg_hba.conf'
- sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
- sudo /etc/init.d/postgresql restart
- sudo psql -U postgres -c "CREATE ROLE travis SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;"
- sudo psql -U postgres -c "CREATE DATABASE travis WITH OWNER = travis;"
- psql --version

- cd backend
- cp profiles.clj.template profiles.clj
- ./provision/setup.sh
- cd ../client
- nvm install 4
- npm config set spin false
- npm install
- cd ../backend

script:
- lein2 do clean, check, test :all
- cd ../client
- npm run lint
- npm test

notifications:
  hipchat:
    rooms:
      secure: rTvHHDbTaoiha4bipdbpSJQJAXpaBiP+tHah6pxRfodSb3S7SvfkBXgctxuNGumVPOCt2efiih51CUxQR4NkOjOLmJI1LgWQmdf9MqUEFz/4Hd9nWB6lYbmbaN/lGEh4pn3NGiWueq6MUO7ORPmVdSOMgH+YBI1U77pJ43NNW5izXrHUNr5xZzZjiYxnFW4pfzuw2iAlnvrHOGPxBQZM8MSqINP2quveqUziBoYmShW4TSHRTV2fpYHEjUbSfq4U2S4mAua9I9QoZjSAuZXFHglmrdNCKlPaXpCouON0uKIecMSu26fDCH8MDq0hcXD5cdm/X+uW6z95UlJVIKyUT02a06G0Bt6OonYox9eJKNFtTxN5aPithM0fa/4r2aXyF5WaSsBFlHKAMhWY4ZbfXj/k9QFsd13aTf7aCRfOAq5VqsTrEW9SgQW5+ID64dWelB3w7MO0pIfe48F3OB2zCnzPwRgH0HA6qMQCRAVDEB0upkt4yIMjURNB74doRfA8DeYhA4ptEDU6X2RCPa5N5B3xJlIheW9I/2RCYRze3zRu7l2CeD+Sg7Vj3O9sqbyj5ZNh6ktw82BNWK2j+igwjk6jy9RaPNsfVEWyOaxjNCyOffd2BeRZP8Gv0CtQP1owc12l9U8SRAt4N1zlAxSp7jZky0hHS4JvT9+PjvZtE6Q=
