version: "3"
services:
 postgres:
   build: postgres
   ports:
    - "5432:5432"
 keycloak:
   build: keycloak
   ports:
    - "8080:8080"
 backend:
   build:
     context: ./backend
     dockerfile: Dockerfile-dev
   volumes:
      - ./backend:/app
      - ~/.m2:/home/akvo/.m2
      - ~/.lein:/home/akvo/.lein
      - ./postgres/provision:/pg-certs
   links:
      - keycloak:auth.lumen.localhost
   ports:
      - "47480:47480"
      - "3000:3000"
   environment:
     - HOST_UID
     - HOST_GID
 client:
   build:
     context: ./client
     dockerfile: Dockerfile-dev
   volumes:
      - ./client:/lumen
   ports:
      - "3030:3030"
   environment:
     - HOST_UID
     - HOST_GID
 redis:
   image: redis:3.2.9
 windshaft:
   build: windshaft
   environment:
     - NODE_ENV=development
     - PGSSLROOTCERT=/pg-certs/server.crt
     - LUMEN_ENCRYPTION_KEY=supersecret
   volumes:
      - ./windshaft/config/dev:/config
      - ./postgres/provision:/pg-certs
