version: "3"
services:
 postgres:
   ports:
    - "5432:5432"
 keycloak:
   ports:
    - "8080:8080"
 backend:
   image: akvo/akvo-lumen-backend-dev:20200610.033159.f413ba3
   volumes:
      - ./backend:/app
      - ~/.m2:/home/akvo/.m2
      - ~/.lein:/home/akvo/.lein
      - ~/.m2:/root/.m2:delegated
      - ~/.lein:/root/.lein:delegated
   ports:
      - "47480:47480"
      - "3000:3000"
   command: ["./import-and-run.sh"]
 client:
   volumes:
      - ./client:/lumen
   ports:
      - "3030:3030"
 windshaft:
   image: akvo/akvo-maps:beaf5cf8
   volumes:
     - ./windshaft/config/dev:/config
 exporter:
   build: exporter
   ports:
      - "3001:3001"
   links:
      - keycloak:auth.lumen.local
      - client:t1.lumen.local
   volumes:
     - ./exporter:/usr/src/app
   command: ["bash", "-c", "npm i && npm start"]
