apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lumen-citest-cleanup
spec:
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 600
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        cronjob: lumen-citest-cleanup
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 900
      template:
        metadata:
          labels:
            cronjob: lumen-citest-cleanup
        spec:
          containers:
          - name: pg-client
            image: postgres:11-alpine
            command: ["/bin/sh", "-c"]
            args:
              - |
                export PGPORT=5432
                export PGHOST="$(echo "$LUMEN_DB_URL" | sed -n 's|.*postgresql://\(.*\):.*|\1|p')"
                export PGUSER="$(echo "$LUMEN_DB_URL" | sed -n 's|.*user=\(.*\)&password.*|\1|p')"
                export PGPASSWORD="$(echo "$LUMEN_DB_URL" | sed -n 's|.*password=\(.*\)|\1|p')"
                export PGSSLMODE=prefer
                export PGDATABASE=tenant_lumencitest
                sleep 10
                trap "touch /tmp/pod/terminated" EXIT
                psql -c "DELETE FROM dataset"
            volumeMounts:
              - mountPath: /tmp/pod
                name: tmp-pod
            resources:
              requests:
                cpu: "50m"
                memory: "256Mi"
              limits:
                cpu: "1000m"
                memory: "256Mi"
            env:
            - name: LUMEN_DB_URL
              valueFrom:
                secretKeyRef:
                  name: lumen
                  key: lumen_db_url
          - name: cloudsql-proxy
            image: eu.gcr.io/cloudsql-docker/gce-proxy:1.15
            command: ["/bin/sh", "-c"]
            args:
              - |
                /cloud_sql_proxy -instances=akvo-lumen:europe-west1:$(GOOGLE_SQL_DB_INSTANCE)=tcp:5432 -credential_file=/secrets/cloudsql/credentials.json &
                CHILD_PID=$!
                (while true; do if [[ -f "/tmp/pod/terminated" ]]; then kill $CHILD_PID; echo "Killed $CHILD_PID because the main container terminated."; fi; sleep 1; done) &
                wait $CHILD_PID
                if [[ -f "/tmp/pod/terminated" ]]; then exit 0; echo "Job completed. Exiting..."; fi
            securityContext:
              runAsUser: 2  # non-root user
              allowPrivilegeEscalation: false
            env:
              - name: GOOGLE_SQL_DB_INSTANCE
                valueFrom:
                  configMapKeyRef:
                    name: akvo-lumen
                    key: google-sql-db-instance
            volumeMounts:
              - name: "secret-config"
                mountPath: "/secrets/cloudsql/credentials.json"
                subPath: "cloud-database-service-account.json"
                readOnly: true
              - mountPath: /tmp/pod
                name: tmp-pod
                readOnly: true
          restartPolicy: Never
          volumes:
            - name: "secret-config"
              secret:
                secretName: "lumen"
            - name: tmp-pod
              emptyDir: {}