apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lumen
  namespace: default
spec:
  tls:
  - hosts:
    - lumen.akvotest.org
    secretName: tls
  rules:
    - host: lumen.akvotest.org
      http:
        paths:
        - backend:
            serviceName: lumen-blue-green-gateway
            servicePort: 80
