name: Main CI

on:
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.5'
    - uses: DeLaGuardo/setup-clojure@1.0
      with:
        lein: 2.9.1

    - name: Unit test
      run: cd backend && lein test
